services:
  - type: web
    name: mero-dokan
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr libtesseract-dev
      pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: OCR_LANGUAGES
        value: eng+nep
      - key: PYTHON_VERSION
        value: "3.11"
